CREATE TABLE IF NOT EXISTS measurements_open_weather_map(
    measurement_id UUID PRIMARY KEY NOT NULL,
    run_id UUID NOT NULL REFERENCES measurement_runs(run_id),
    time_zone TEXT NOT NULL,
    time_zone_offset INTEGER NOT NULL,
    time_current BIGINT NOT NULL,
    time_sunrise BIGINT NOT NULL,
    time_sunset BIGINT NOT NULL,
    temperature FLOAT NOT NULL,
    feels_like FLOAT NOT NULL,
    pressure FLOAT NOT NULL,
    humidity FLOAT NOT NULL,
    dew_point FLOAT NOT NULL,
    uv_index FLOAT NOT NULL,
    clouds FLOAT NOT NULL,
    visibility BIGINT NOT NULL,
    wind_speed FLOAT NOT NULL,
    wind_direction FLOAT NOT NULL,
    wind_gust FLOAT NOT NULL,
    weather_object_id INTEGER NOT NULL,
    weather_object_main TEXT NOT NULL,
    weather_object_description TEXT NOT NULL,
    weather_object_icon TEXT NOT NULL,
    time_stamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);